name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: solplex-android-apk
          path: bin/*.apk
