name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
            libffi-dev libssl-dev libsqlite3-dev ccache cmake lld build-essential

      - name: Install Buildozer & Pin Cython
        run: |
          pip install --upgrade pip setuptools virtualenv
          pip install "cython<3.0" buildozer

      - name: Build APK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | buildozer android debug
